name: SlimeHUD

author: SchnTgaiSpock

description: 黏液科技附加 黏液顯示器 繁體翻譯版.

main: io.github.schntgaispock.slimehud.SlimeHUD

website: https://github.com/SchnTgaiSpock/SlimeHUD

version: ${project.version}

api-version: 1.14

depend:
- Slimefun

commands:
  slimehud:
    description: /slimehud
    aliases: [sfhud, sfh]
    usage: Press [tab] for usage hints

permissions:
  slimehud.togglewaila:
    description: Able to toggle the WAILA HUD
    default: true